name: Build EXE

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Test imports
        run: |
          cd src && python -c "
          import sys
          import warnings
          warnings.filterwarnings('ignore')
          
          print('Testing core imports...')
          import tkinter
          print('[OK] tkinter')
          
          import cv2
          print('[OK] opencv-python')
          
          import numpy
          print('[OK] numpy') 
          
          import sklearn.linear_model
          print('[OK] sklearn')
          
          import joblib
          print('[OK] joblib')
          
          import ephem
          print('[OK] ephem')
          
          import pytz
          print('[OK] pytz')
          
          try:
              import astropy.io.fits
              print('[OK] astropy')
          except ImportError as e:
              print(f'[WARN] astropy import issue: {e}')
          
          print('All core imports successful!')
          "

      - name: Build EXE with pyinstaller
        run: |
          echo "Building with PyInstaller..."
          pyinstaller synthetic_roofstatus.spec --clean --noconfirm
          
          echo "Checking build output..."
          if (Test-Path "dist/Synthetic_RoofStatusFile.exe") {
            $fileInfo = Get-Item "dist/Synthetic_RoofStatusFile.exe"
            Write-Host "[SUCCESS] Build completed!"
            Write-Host "File size: $([math]::Round($fileInfo.Length / 1MB, 2)) MB"
          } else {
            Write-Error "Build failed - executable not found"
            exit 1
          }

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Synthetic_RoofStatusFile
          path: dist/Synthetic_RoofStatusFile.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Synthetic_RoofStatusFile.exe
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
